MAIL:
  HOST: ""
  PORT: "25"
  USER: ""
  # BATCH: 200
JWT:
  EXPIRATION:
    LONG: 5000
    SHORT: 200
OTP:
  EXPIRATION: 20
  SIZE: 6
DATABASE:
  HOST: "localhost"
  PORT: "5432"
  USER: "admin"
  PASSWORD: "b2Led2ke"
DBNAME:
  APPLICATION: "application"
  COMPANY: "company"
  RC: "rc"
  STUDENT: "student"
  AUTH: "auth"
PORT:
  RAS: 3470
  AUTH: 3475
  STUDENT: 3480
  COMPANY: 3485
  ADMIN:
    RC: 3490
    APP: 3492
    COMPANY: 3495
    STUDENT: 3500
